language: go
go:
- 1.8.x
services:
  - mongodb
before_install:
  - wget https://s3.amazonaws.com/sico-ops/config.travis.json -O controller/config.json
install:
  - go get -t ./...
script: go test -test.bench=".*" -v ./controller/...
notifications:
  slack:
    secure: fLZk4rHTR/EYL4xjGnQd3Vy3O9MVEldiNnTcCxNC5/XvIZcJGdLGAZkr0jA3g5p2nQRJBS82+Jvtn/AIZuHay2iwRbxQQ4LuqPRyaqnU35oiRUONQM//T6XUGu1tkd9GhsEzkWgaVxJ1+UksM5nHGvVnX1Yr8HN6fX1+Rv/ij1Ph7t/RjWL/FxJYVgYGzZEfhBYTTErTgY7j9slobTiavmO8bk5NUIz9OgtY2ybKPyLR2fATvAyI53kDLRAYBhgdTTdjpmjdMeW91B1w0FFJ/SrVoqfPhTGjiSZtajqzqmyGOpL5wAIuufxKkt7wOLrhbLm9TBVav2FbLC12Uupsyvp70JVk87GB0r8nKzkFWpseHVYDA4TbDq5wtLjc5V11xbGgjSX9/2kdhGL4jmlHLksA6amAQaZPhykdgGgkwKunqfBWsjlJCWNHE/K5HGLxgn9bPBLX7/EurKNxg7kJy9WWjH1V3z9aa9hXYD59zJrYJ3F8KlGr5bK2IjMjWbo4sS/yfd3XGeTyoLcv3d6Uk2TkyrDMmVO9oV7MwGkIsbGPFmsm8/FYH8GF+mWYBVqHasVp6swBoEJ6gtgxIiY9BxYr/vDtgsR5e/+X20RFjkQBiPRL3YAt17LwPJ34TBYvCtXSgHcSTyXlfJ14tbQ+pJGJjj2+Vl4O2W5O5pLPj5w=